WebUI/Controllers/SearchController.cs
using System;
using System.Web;
using System.Web.Mvc;
using WebUI.ViewModel;

namespace WebUI.Controllers
{
    public sealed class SearchController : Controller
    {
        public SearchController()
        {
            _searchService = new RemoteSearchService.SearchService();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetSearchResult(
            string query,
            int page,
            bool isCustomRangeEnable)
        {
            var userId = GetUserId();
            var searchResult = _searchService.Search(
                query,
                page,
                true,
                userId.ToString(),
                isCustomRangeEnable,
                true);

            var searchVewModel = new SearchResultViewModel(
                searchResult,
                new SearchZoneViewModel(
                    query,
                    isCustomRangeEnable,
                    page));

            return View("SearchResult", searchVewModel);
        }

        [HttpGet]
        public ActionResult NewSearch(
            string query,
            bool isCustomRangeEnable)
        {
            return GetSearchResult(
                query,
                0,
                isCustomRangeEnable);
        }

        [HttpGet]
        public RedirectResult RegistrateTransition(
            string redirectionUrl,
            int fileId,
            bool isNeedCustomRange)
        {
            var userId = GetUserId();

            if (isNeedCustomRange)
            {
                _searchService.MarkAsLiked(
                    userId.ToString(),
                    fileId,
                    true);    
            }

            return Redirect(redirectionUrl);
        }

        private Guid GetUserId()
        {
            string userIdString;
            if (Request.Cookies[UserIdKey] == null)
            {
                userIdString = Guid.NewGuid().ToString();
                var userIdCookie = new HttpCookie(
                    UserIdKey,
                    userIdString)
                {
                    Expires = DateTime.Now.AddDays(1)
                };

                Response.SetCookie(userIdCookie);
            }
            else
            {
                userIdString = Request.Cookies[UserIdKey].Value;
            }

            return Guid.Parse(userIdString);
        }

        private const string UserIdKey = "UserId";
        private readonly RemoteSearchService.SearchService _searchService;
    }
}

WebUI/Views/Search/Index.cshtml
@using WebUI.ViewModel
@{
    ViewBag.Title = "Stackoverflow Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="centered-main">
    <div class="search-form">
        <div class="search-header">
            <img src="~/Images/stackoverflow.png" /> 
        </div>
        
        @Html.Partial(
            "SearchZone",
            new SearchZoneViewModel(
                userQuery: "",
                isCustomRangeEnable: false,
                pageNumber: 0))
     </div>
</div>

WebUI/Views/Search/SearchResult.cshtml
@using WebUI
@model WebUI.ViewModel.SearchResultViewModel

@{
    ViewBag.Title = Model.SearchZoneParams.UserQuery;

    var startPage = Model.SearchZoneParams.PageNumber;
    if (Model.SearchZoneParams.PageNumber != 0)
    {
        startPage--;
    }

    var lastPage = Model.PagesCount;
    if ((lastPage - startPage) > WebConstants.PaginationsCount)
    {
        lastPage = startPage + WebConstants.PaginationsCount;
    }

    if ((lastPage - startPage) < WebConstants.PaginationsCount)
    {
        startPage = lastPage - WebConstants.PaginationsCount;
    }

    if (startPage < 0)
    {
        startPage = 0;
    }
}

<div class="result-zone">
    <div class="head-search">
        @Html.Partial("SearchZone", Model.SearchZoneParams)
    </div>
    
    <div class="verdana-text  result-count">
        There is @Model.SearchResult.ResultsCount results.
    </div>
    
    
    <div class="search-results">
        @foreach (var snippet in Model.SearchResult.Snippets)
        {
            <div class="search-result">
                @Html.ActionLink(
                    String.IsNullOrEmpty(snippet.SnippetText) ? "SomeText" : snippet.SnippetText,
                    "RegistrateTransition",
                    new RouteValueDictionary
                    {
                        {"redirectionUrl", snippet.SnippetUrl},
                        {"fileId", snippet.FileId},
                        {"isNeedCustomRange", Model.SearchZoneParams.IsCustomRangeEnable}
                    })

                <div class="result-link">
                    @Html.ActionLink(
                    snippet.SnippetUrl,
                    "RegistrateTransition",
                    new RouteValueDictionary
                    {
                        {"redirectionUrl", snippet.SnippetUrl},
                        {"fileId", snippet.FileId},
                        {"isNeedCustomRange", Model.SearchZoneParams.IsCustomRangeEnable}
                    })
                </div>
                
                <div class="result-tag-list">
                    @foreach (var tag in snippet.Tags)
                    {
                        <span class="result-tag">@tag</span>
                    }
                </div>
            </div>
        }
    </div>

    <div class="paggination-zone">
        @for (var i = startPage; i < lastPage; i++)
        {
            if (i == Model.SearchZoneParams.PageNumber)
            {
                @:
                <span class="page-number"> @(i + 1) </span>
            }
            else
            {
                @:   
                <span class="page-number">
                    @Html.ActionLink((i + 1).ToString(), "GetSearchResult", new RouteValueDictionary
                    {
                        {"query", Model.SearchZoneParams.UserQuery},
                        {"page", i},
                        {"isCustomRangeEnable", Model.SearchZoneParams.IsCustomRangeEnable}
                    })
                </span>
            }
        } 
    </div>
</div>

WebUI/Views/Search/SearchZone.cshtml
@model WebUI.ViewModel.SearchZoneViewModel

@using (Html.BeginForm("NewSearch", "Search", FormMethod.Get))
{
    @Html.TextBox(
        "query",
        Model.UserQuery,
        new Dictionary<string, object> 
        { 
            { "class", "search-input" }
        })
    
    <div class="custom-range">
        <span>Собирать о вас данные? </span>
        
        @Html.CheckBox("isCustomRangeEnable", Model.IsCustomRangeEnable)
    </div>
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" href="@Url.Content("~/Images/favicon.ico")" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <body>
            @RenderBody()
    </body>
</html>